# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emetadata.proto\"&\n\x16GetFileMetaDataRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\"E\n\x17GetFileMetaDataResponse\x12\x17\n\x0fpeer_ip_address\x18\x01 \x01(\t\x12\x11\n\tpeer_port\x18\x02 \x01(\x05\x32P\n\x08Metadata\x12\x44\n\x0fGetFileMetaData\x12\x17.GetFileMetaDataRequest\x1a\x18.GetFileMetaDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metadata_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GETFILEMETADATAREQUEST']._serialized_start=18
  _globals['_GETFILEMETADATAREQUEST']._serialized_end=56
  _globals['_GETFILEMETADATARESPONSE']._serialized_start=58
  _globals['_GETFILEMETADATARESPONSE']._serialized_end=127
  _globals['_METADATA']._serialized_start=129
  _globals['_METADATA']._serialized_end=209
# @@protoc_insertion_point(module_scope)
